In [6]:
import pandas as pd

# Load all datasets
daily_activity = pd.read_csv("../data/dailyActivity_merged.csv")
heartrate = pd.read_csv("../data/heartrate_seconds_merged.csv")
hourly_calories = pd.read_csv("../data/hourlyCalories_merged.csv")
hourly_intensities = pd.read_csv("../data/hourlyIntensities_merged.csv")
hourly_steps = pd.read_csv("../data/hourlySteps_merged.csv")
minute_calories = pd.read_csv("../data/minuteCaloriesNarrow_merged.csv")
minute_intensities = pd.read_csv("../data/minuteIntensitiesNarrow_merged.csv")
minute_mets = pd.read_csv("../data/minuteMETsNarrow_merged.csv")
minute_sleep = pd.read_csv("../data/minuteSleep_merged.csv")
minute_steps = pd.read_csv("../data/minuteStepsNarrow_merged.csv")
weight_log = pd.read_csv("../data/weightLogInfo_merged.csv")

In [7]:
# Import libraries
import pandas as pd
import numpy as np

# Load the datasets
daily_activity = pd.read_csv("../data/dailyActivity_merged.csv")
sleep = pd.read_csv("../data/minuteSleep_merged.csv")
weight = pd.read_csv("../data/weightLogInfo_merged.csv")

# Preview the data
daily_activity.head()

,Id,ActivityDate,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories
0,1503960366,3/25/2016,11004,7.11,7.11,0.0,2.57,0.46,4.07,0.0,33,12,205,804,1819
1,1503960366,3/26/2016,17609,11.55,11.55,0.0,6.92,0.73,3.91,0.0,89,17,274,588,2154
2,1503960366,3/27/2016,12736,8.53,8.53,0.0,4.66,0.16,3.71,0.0,56,5,268,605,1944
3,1503960366,3/28/2016,13231,8.93,8.93,0.0,3.19,0.79,4.95,0.0,39,20,224,1080,1932
4,1503960366,3/29/2016,12041,7.85,7.85,0.0,2.16,1.09,4.61,0.0,28,28,243,763,1886

In [ ]:
datasets = {
    "dailyActivity_merged.csv": daily_activity,
    "heartrate_seconds_merged.csv": heartrate,
    "hourlyCalories_merged.csv": hourly_calories,
    "hourlyIntensities_merged.csv": hourly_intensities,
    "hourlySteps_merged.csv": hourly_steps,
    "minuteCaloriesNarrow_merged.csv": minute_calories,
    "minuteIntensitiesNarrow_merged.csv": minute_intensities,
    "minuteMETsNarrow_merged.csv": minute_mets,
    "minuteSleep_merged.csv": minute_sleep,
    "minuteStepsNarrow_merged.csv": minute_steps,
    "weightLogInfo_merged.csv": weight_log
}

for name, df in datasets.items():
    print(f"\n📊 Dataset: {name}")
    print("-" * 50)
    print("Shape:", df.shape)
    print("Missing values:\n", df.isnull().sum())
    print("Duplicate rows:", df.duplicated().sum())
    print("Data types:\n", df.dtypes)
    print("Descriptive statistics:\n", df.describe())
    print("\n")

In [9]:
# 🔁 Remove duplicates in minuteSleep_merged
print("Before removing duplicates:", minute_sleep.duplicated().sum())
minute_sleep_cleaned = minute_sleep.drop_duplicates()
print("After removing duplicates:", minute_sleep_cleaned.duplicated().sum())

# 🧩 Handle missing values in weightLogInfo_merged
# Check missing values
print("\nMissing values in weight_log:")
print(weight_log.isnull().sum())

# Since 'Fat' column has 31 missing out of 33 rows, it's nearly all missing.
# We'll drop the 'Fat' column entirely for now
weight_log_cleaned = weight_log.drop(columns=["Fat"])

# Verify changes
print("\nColumns in cleaned weight_log:")
print(weight_log_cleaned.columns)

Before removing duplicates: 525
After removing duplicates: 0

Missing values in weight_log:
Id                 0
Date               0
WeightKg           0
WeightPounds       0
Fat               31
BMI                0
IsManualReport     0
LogId              0
dtype: int64

Columns in cleaned weight_log:
Index(['Id', 'Date', 'WeightKg', 'WeightPounds', 'BMI', 'IsManualReport',
       'LogId'],
      dtype='object')

In [17]:
minute_sleep.head()

           Id                  date  value        logId
0  1503960366  3/13/2016 2:39:30 AM      1  11114919637
1  1503960366  3/13/2016 2:40:30 AM      1  11114919637
2  1503960366  3/13/2016 2:41:30 AM      1  11114919637
3  1503960366  3/13/2016 2:42:30 AM      1  11114919637
4  1503960366  3/13/2016 2:43:30 AM      1  11114919637